# Generated by Django 3.2.2 on 2021-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
