# Generated by Django 3.2.2 on 2021-05-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20210512_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='web',
        ),
    ]
