# Generated by Django 3.2.2 on 2021-05-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_remove_perfil_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='password',
            field=models.CharField(default='nulo', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
