# Generated by Django 3.2.2 on 2021-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20210514_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cvc',
            field=models.FileField(blank=True, null=True, upload_to='cvcusuarios/', verbose_name='Curriculum'),
        ),
    ]
