# Generated by Django 3.2.2 on 2021-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_alter_perfil_cvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telf_usuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Teléfono'),
        ),
    ]
