# Generated by Django 3.2.2 on 2021-05-22 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 15, 12, 25, 703680, tzinfo=utc)),
        ),
    ]
