# Generated by Django 3.2.2 on 2021-05-22 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0009_alter_oferta_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 15, 23, 36, 612491, tzinfo=utc)),
        ),
    ]
