# Generated by Django 3.2.2 on 2021-05-22 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0010_alter_oferta_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
