# Generated by Django 3.2.2 on 2021-05-22 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0011_alter_oferta_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='oferta',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='oferta',
            name='experiencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
