# Generated by Django 3.2.2 on 2021-05-23 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0012_auto_20210522_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.oferta')),
            ],
        ),
    ]
