# Generated by Django 3.2.2 on 2021-05-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0013_candidaturas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidaturas',
            new_name='Candidatura',
        ),
    ]
